# Generated by Django 4.2.20 on 2025-05-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_gamestate_map_gamestate_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_guest_user',
            field=models.BooleanField(default=True),
        ),
    ]
